spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issue_tracker?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jdbc:
      repositories:
        enabled: true