name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Backend (Skip tests)
        working-directory: backend
        run: |
          ./gradlew clean build -x test
          ls -l build/libs/

      - name: Upload jar to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: backend/build/libs/
          target: /home/ubuntu/issue-tracker/backend/build/libs

      - name: Deploy and run backend on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            PROJECT_NAME="issue-tracker"
            BACKEND_DIR="/home/ubuntu/$PROJECT_NAME"
            JAR_NAME="issue-tracker-0.0.1-SNAPSHOT.jar"
            BUILD_DIR="$BACKEND_DIR/backend/build/libs"
            LOG_FILE="/home/ubuntu/nohup.out"

            echo "🛑 기존 백엔드 종료..."
            PID=$(pgrep -f $JAR_NAME) || true
            if [ -n "$PID" ]; then
              kill -9 $PID
              echo "✅ 종료 완료 (PID=$PID)"
            else
              echo "⚠️ 실행 중인 백엔드 없음"
            fi

            echo "🚀 백엔드 실행 중..."
            nohup java -jar $BUILD_DIR/$JAR_NAME > $LOG_FILE 2>&1 &
