name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy and Run on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          
          # 로그 디렉토리 준비
          sudo mkdir -p /var/log/issue-tracker
          sudo chown $(whoami):$(whoami) /var/log/issue-tracker

          # 프로젝트 디렉토리로 이동
          cd ~/issue-tracker

          # 최신 코드 pull
          git checkout main
          git pull origin main

          # 빌드
          chmod +x ./gradlew
          ./gradlew -p backend build -x test

          # 기존 실행 중인 서버 종료
          pkill -f 'java -jar' || true

          # 실행
          nohup java -jar backend/build/libs/backend-0.0.1-SNAPSHOT.jar > /var/log/issue-tracker/app.log 2>&1 &
          EOF
